'use strict';

var express = require('express'),
    zones = express.Router(),
    Model = require('../models/model-users.js');

/**
* @api {get} /jabeja/api/zone getZones.
* @apiName getZones
* @apiGroup Zone
* @apiSuccess {Array} zones  Array of zone information in json.
* @apiFailure {Number} 500  Error getting zones.
*
* @apiSuccessExample Success-Response:
*     HTTP/1.1 200 OK
*     [
*       {
*         "zoneId": "123123123213123123123",
*         "title_en": "washington",
*         "title_fa": "واشنگتن",
*         "country_en": "USA",
*         "country_fa": "آمریکا"
*       }
*     ]
*
* @apiFailureExample Failure-Response:
*     HTTP/1.1 500 Error
*     {
*      "message" : "Error getting zones."
*     }
*
*/
zones.get('/', function(req, res) {
    Model.find(function(err, zones){
        if(err) {
            return res.json(500, {
                message: 'Error getting zones.'
            });
        }
        return res.json(zones);
    });
});

/**
* @api {post} /jabeja/api/zone addZone.
* @apiName addZone
* @apiGroup Zone
*
* @apiParam {String} zoneId  Zone Id.
* @apiParam {String} title_en  Zone english title.
* @apiParam {String} title_fa  Zone farsi title.
* @apiParam {String} country_en  Country english title.
* @apiParam {String} country_fa  Country farsi title.
* @apiSuccess {String} saved saved.
* @apiSuccess {String} zoneId Zone Id generated by front-edn (Hashing the zone title).
* @apiFailure {Number} 500  Error saving item.
*
* @apiSuccessExample Success-Response:
*     HTTP/1.1 200 OK
*     {
*       message: 'saved',
*       zoneId: "@#asdiuhiuh123;`oij123"
*     }
*
* @apiFailureExample Failure-Response:
*     HTTP/1.1 500 Error
*     {
*      "message" : "Error saving item.",
*      error: "ERROR Detail"
*     }
*
*/
zones.post('/', function(req, res) {
    var zone = new Model({
        'zoneId': req.body['zoneId'],
        'title_en': req.body['title_en'],
        'title_fa': req.body['title_fa'],
        'country_en': req.body['country_en'],
        'country_fa': req.body['country_fa']
    });
    zone.save(function(err, zone){
        if(err) {
            return res.json(500, {
                message: 'Error saving item.',
                error: err
            });
        }
        return res.json({
            message: 'saved',
            zoneId: zone.zoneId
        });
    });
});

module.exports = zones;
